### ISSUE TITLE
RUST_BACKTRACE=1, thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', 

### ISSUE THREAD

**Issue by odealmervea** [Qovery/Replibyte#138]
1)docker: Error response from daemon: create $(pwd)/examples: "$(pwd)/examples" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

2)thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', replibyte/src/main.rs:82:40
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context
USAGE:
replibyte transformer list
For more information try --help

3)error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context
USAGE:
replibyte [OPTIONS] --config
For more information try --help

i am getting these errors
Can u help me
thanks from now

**Comment by Tchoupinax** [comment]
Hello @odealmervea,

I had the same issue with using the local datastore and it is solved by upgrading to v0.8.3. I think there was a bug which is solved by the last merged PR.

Hope it will help you,
Have a nice day.

**Comment by evoxmusic** [comment]
Hi, I am going to take a look ASAP

**Comment by evoxmusic** [comment]
> 1)docker: Error response from daemon: create (pwd)/examples:"(pwd)/examples" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. See 'docker run --help'.
> 
> 2)thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', replibyte/src/main.rs:82:40 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte transformer list For more information try --help
> 
> 3)error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte [OPTIONS] --config For more information try --help
> 
> i am getting these errors Can u help me thanks from now

Can you check if your issue is solved? Thx

**Comment by odealmervea** [comment]
> > 1)docker: Error response from daemon: create (pwd)/examples:"(pwd)/examples" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. See 'docker run --help'.
> > 2)thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', replibyte/src/main.rs:82:40 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte transformer list For more information try --help
> > 3)error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte [OPTIONS] --config For more information try --help
> > i am getting these errors Can u help me thanks from now
> 
> Can you check if your issue is solved? Thx

Unfortunately, the problem is not solved.

**Comment by odealmervea** [comment]
> > 1)docker: Error response from daemon: create (pwd)/examples:"(pwd)/examples" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. See 'docker run --help'.
> > 2)thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', replibyte/src/main.rs:82:40 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte transformer list For more information try --help
> > 3)error: Found argument 'RUST_BACKTRACE=1' which wasn't expected, or isn't valid in this context USAGE: replibyte [OPTIONS] --config For more information try --help
> > i am getting these errors Can u help me thanks from now
> 
> Can you check if your issue is solved? Thx

****
'replibyte' is not recognized as an internal or external command,
operable program or batch file.'replibyte' is not recognized as an internal or external command,
operable program or batch file.

I'm getting this error

**Comment by fabriceclementz** [comment]
Hi @odealmervea 
Maybe this can help you ? https://github.com/Qovery/Replibyte/issues/147

**Comment by michaelgrigoryan25** [comment]
@odealmervea, do you still have this issue? If so, can you set `RUST_BACKTRACE` to `1` in the environment variables, or the command-line, and run the application again, so that we can debug this?

**Comment by coderberry** [comment]
This issue is still happening for me. Here are my results:

```
➜ RUST_BACKTRACE=1 replibyte -c ./conf.yaml dump list
thread 'main' panicked at 'missing config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', replibyte/src/main.rs:86:40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: replibyte::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
