### ISSUE TITLE
Unexpected EOF while in a multi-line comment

### ISSUE THREAD

**Issue by manibatra** [Qovery/Replibyte#190]
I am getting the following error : 

```
failing query: '/*
FOR EACH ROW
BEGIN
  IF NEW.createdAt IS NULL THEN
    SET NEW.createdAt = NOW();'
thread 'main' panicked at 'TokenizerError { message: "Unexpected EOF while in a multi-line comment", line: 1, col: 1 }', dump-parser/src/mysql/mod.rs:708:13
stack backtrace:
⠁
   0:        0x101ac7072 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x101aee6bb - core::fmt::write::hb68c3045179d0cad
   2:        0x101abebce - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x101ac9990 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x101ac9676 - std::panicking::default_hook::ha3efe84526f027fa
   5:        0x101aca0ed - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   6:        0x101ac9e13 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   7:        0x101ac7507 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   8:        0x101ac9ada - _rust_begin_unwind
   9:        0x101b4e763 - core::panicking::panic_fmt::hf7d6e5207e013f69
  10:        0x1015196cb - dump_parser::mysql::get_tokens_from_query_str::hcd45d94ce6efca1c
  11:        0x100ef0d2c - replibyte::source::mysql::read_and_transform::{{closure}}::he6272ec724e78e22
  12:        0x100ee7578 - dump_parser::utils::list_sql_queries_from_dump_reader::h8dd3cdf032548fbb
  13:        0x100e63819 - replibyte::source::mysql::read_and_transform::hae51fcd666d8fbfe
  14:        0x100e68286 - <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run::he131302926c77628
  15:        0x100e4e36c - replibyte::commands::dump::run::h0cdadc3aace7d69b
  16:        0x100ebd2a1 - replibyte::main::h1d4c614d492e4f7c
  17:        0x100f50f86 - std::sys_common::backtrace::__rust_begin_short_backtrace::h56ffaf9859a24ce2
  18:        0x100ea27dc - std::rt::lang_start::{{closure}}::hb61de73412d26ca9
  19:        0x101ac67a5 - std::rt::lang_start_internal::hef78d5782ed29805
  20:        0x100ec2d79 - _main
```

So the following does not work : 
```
/*
FOR EACH ROW
BEGIN
  IF NEW.createdAt IS NULL THEN 
    SET NEW.createdAt = NOW();
   END IF;
  IF NEW.updatedAt IS NULL THEN
    SET NEW.updatedAt = NOW();
  END IF;
END */

```

I am running the following command : 
```
cat mini.sql | replibyte -c conf.yaml dump create -i -s mysql
```

```
❯ replibyte --version
replibyte 0.9.1
```

**Comment by evoxmusic** [comment]
@manibatra can you show me your replibyte conf yaml?

**Comment by manibatra** [comment]
Sure thing : 
```
source:
  transformers:
    - database: management
      table: cluster
      columns:
        - name: token
          transformer_name: random
datastore:
  local_disk:
    dir: /Users/mani/
```

**Comment by evoxmusic** [comment]
Fyi Replibyte has been updated a few hours ago. Couple of fix have been released for MySQL source connector. Can you check if this bug has been fixed with the latest version?

**Comment by adithya321** [comment]
Getting the same error in Postgres

```
replibyte --version
replibyte 0.9.5
```

`replibyte-conf.yaml`

```yaml
source:
 connection_uri: $DATABASE_URL

datastore:
 local_disk:
  dir: ./data
```

```
RUST_BACKTRACE=full replibyte -c replibyte-conf.yaml dump create
```

```
⠖ [00:00:13] [#############################################>----------------] 19.44MiB/100.00MiB (56s)
failing query: '');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9006, 'System:8g*9/*7T&G#R', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', '8g*9/*7T&G#R');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9007, 'System:cp&''X(%JnL5m', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'cp&''X(%JnL5m');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9008, 'System:piRKpIImGa2v', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'piRKpIImGa2v');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9009, 'System:6!Zbjd''dwX"z', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', '6!Zbjd''dwX"z');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9010, 'System:c0KEN_%*IsLV', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'c0KEN_%*IsLV');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9011, 'System:sHFzJ3]ep,tw', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'sHFzJ3]ep,tw');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9012, 'System:]p"-ZjtUfBrD', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', ']p"-ZjtUfBrD');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9013, 'System:(AUG''8+<8?do', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', '(AUG''8+<8?do');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9014, 'System:"81%xPR/%?d_', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', '"81%xPR/%?d_');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9015, 'System:Nxik,rTNG6$A', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'Nxik,rTNG6$A');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9016, 'System:bOU,Fb$0vS%Z', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'bOU,Fb$0vS%Z');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9017, 'System:j)iE8SooIo''0', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'j)iE8SooIo''0');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9018, 'System:*"R.FBbcj%1F', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', '*"R.FBbcj%1F');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9019, 'System:)RgrF=@w1m6X', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', ')RgrF=@w1m6X');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9020, 'System:x!b5#''Y5[/n:', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'x!b5#''Y5[/n:');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9021, 'System:hK-%&DUw7ip.', '2022-07-22 13:36:17.860761+00', '2022-07-22 13:36:17.860761+00', 'hK-%&DUw7ip.');
INSERT INTO public.tag (id, name, created_at, updated_at, code) VALUES (9022, 'System:%koo,DQ1&;'
thread 'main' panicked at 'TokenizerError { message: "Unexpected EOF while in a multi-line comment", line: 1, col: 8 }', dump-parser/src/postgres/mod.rs:761:13
stack backtrace:
   0:        0x1055c50f2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x1055ec73b - core::fmt::write::hb68c3045179d0cad
   2:        0x1055bcc4e - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x1055c7a10 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x1055c76f6 - std::panicking::default_hook::ha3efe84526f027fa
   5:        0x1055c816d - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   6:        0x1055c7e93 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   7:        0x1055c5587 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   8:        0x1055c7b5a - _rust_begin_unwind
   9:        0x10564c7e3 - core::panicking::panic_fmt::hf7d6e5207e013f69
  10:        0x10501328b - dump_parser::postgres::get_tokens_from_query_str::hfc433f791d0448ad
  11:        0x1049f420c - replibyte::source::postgres::read_and_transform::{{closure}}::h4adcfb1516460543
  12:        0x1049e65af - dump_parser::utils::list_sql_queries_from_dump_reader::h121036df8a31551c
  13:        0x10498495b - <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run::h25eb25d125125c57
  14:        0x104940786 - replibyte::commands::dump::run::hdde2183f45de9b40
  15:        0x1049d076c - replibyte::main::h5e4911826d5385da
  16:        0x104a4d9e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h008ebbc4e489083e
  17:        0x1049a648c - std::rt::lang_start::{{closure}}::h017fbcffc8c9eeda
  18:        0x1055c4825 - std::rt::lang_start_internal::hef78d5782ed29805
  19:        0x1049d6369 - _main
```

**Comment by adithya321** [comment]
@evoxmusic v0.9.6 fixed the above issue 🎉 Thank you
