### ISSUE TITLE
PostgreSQL: Unexpected EOF while in a multi-line comment

### ISSUE THREAD

**Issue by mridude23** [Qovery/Replibyte#230]
Hi team,

While trying to subset a database of around 85 gb with a lot of foreign keys between tables I get the following error: (I am swapping table names and columns but keeping logic)
```
⠒ [00:47:28] [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0B/100.00MiB (0s)
failing query: '    /* 3. Number of instrument with no primary t4 id set and also without information in t2 listing
    insert into prl_discrepancies
    select t1.t1id, t2.type, t5.name, 'none_list_id' as errType
    from t1
        inner join t2 on t2.t2id = t1.t1id
        inner join t3 on t3.t3id = t1.t1id and t3.t3eid = t1.t1eid and t3.todate >= current_date
        inner join t4 on t4.t4id = t1.t1eid
        inner join t5 on t4.t4ctyid = t5.t5id
        inner join t6 on t6.t6id = t5.t5cttid
    where t1.active = 1 and t1.longname is not null
        and t2.someid is null
        and coalesce(_type, t2.type) = t2.type
    group by t1.t1id, t2.type, t5.name
    having sum(case when t3.istrue = 'Y' then 1 else 0 end) < 1;'
thread 'main' panicked at 'TokenizerError { message: "Unexpected EOF while in a multi-line comment", line: 1, col: 5 }', dump-parser/src/postgres/mod.rs:824:13
⠙ [00:47:28] [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0B/100.00MiB (0s)
   0:     0x7f1e5f25ff8d - std::backtrace_rs::backtrace::libunwind::trace::h081201764674ef17
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1e5f25ff8d - std::backtrace_rs::backtrace::trace_unsynchronized::hebab37398c391bd7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1e5f25ff8d - std::sys_common::backtrace::_print_fmt::h301516df68ed24f9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f1e5f25ff8d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f5170f4f03a12c0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f1e5f2aba6c - core::fmt::write::h5dc5601e8d9f6367
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f1e5f257bf8 - std::io::Write::write_fmt::h5b19302eb99d9acf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f1e5f262497 - std::sys_common::backtrace::_print::hd81cf53a75c8ae6a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f1e5f262497 - std::sys_common::backtrace::print::hb5aa882e87c2a0dc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f1e5f262497 - std::panicking::default_hook::{{closure}}::had913369af61b326
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f1e5f262160 - std::panicking::default_hook::h37b06af9ee965447
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f1e5f262be9 - std::panicking::rust_panic_with_hook::hf2019958d21362cc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7f1e5f2628d7 - std::panicking::begin_panic_handler::{{closure}}::he9c06fdd592f8785
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7f1e5f260454 - std::sys_common::backtrace::__rust_end_short_backtrace::ha521b96560789310
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f1e5f2625e9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7f1e5e3c9b93 - core::panicking::panic_fmt::h28f1697d4e9394b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7f1e5ecd62ae - dump_parser::postgres::get_tokens_from_query_str::h65e24e4f8cbc8f6b
⠠ [00:47:28] [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0B/100.00MiB (0s)
  17:     0x7f1e5ecb90a1 - dump_parser::utils::list_sql_queries_from_dump_reader::he38dab96aeccb7e2
  18:     0x7f1e5ecb530f - subset::postgres::PostgresSubset::new::h3bf13aa8e13bb75e
  19:     0x7f1e5e46fc80 - <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run::hbe436c3f9a64d91e
  20:     0x7f1e5e418b26 - replibyte::commands::dump::run::h2c7a4f7f319ea54d
  21:     0x7f1e5e4db59c - replibyte::main::hf5aea629140e0d3d
  22:     0x7f1e5e40d433 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd939a912bfcc1f10
  23:     0x7f1e5e493ad9 - std::rt::lang_start::{{closure}}::h7bad7a965e7c4d15
  24:     0x7f1e5f25f6e4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd127f27863548251
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  25:     0x7f1e5f25f6e4 - std::panicking::try::do_call::h926290883a1d024e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  26:     0x7f1e5f25f6e4 - std::panicking::try::hc74a3d1f4a4b6e5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  27:     0x7f1e5f25f6e4 - std::panic::catch_unwind::h5eb7ded2df1a4d5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  28:     0x7f1e5f25f6e4 - std::rt::lang_start_internal::{{closure}}::h0736f9682f7c55ea
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  29:     0x7f1e5f25f6e4 - std::panicking::try::do_call::h2772c479b1c89ef7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  30:     0x7f1e5f25f6e4 - std::panicking::try::h967ebbc371287391
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  31:     0x7f1e5f25f6e4 - std::panic::catch_unwind::h41bcc02b28316856
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  32:     0x7f1e5f25f6e4 - std::rt::lang_start_internal::haf46799f55774d07
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
⠲ [00:47:29] [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0B/100.00MiB (0s)

```

My `conf.yaml` file looks like this:
```
#encryption_key: $MY_PRIVATE_ENC_KEY # optional - encrypt data on datastore
source:
  connection_uri: postgres://postgres:postgres@localhost:5435/test# you can use $DATABASE_URL
  database_subset:
    database: test
    table: some_table
    strategy_name: random
    strategy_options:
      percent: 5
    passthrough_tables:
      - t4
      - t5
      - t6
      - curent
      - sector
datastore:
  local_disk:
    dir: /var/lib/pgsql/replibyte_dumps
#destination:
#  connection_uri: postgres://postgres:postgres@localhost:5432/subset_test # you can use $DATABASE_URL
```

I tried with the latest 2 versions and the error is the same. 
```
-bash-4.2$ ./replibyte --version
replibyte 0.9.7
```
```
-bash-4.2$ ./replibyte --version
replibyte 0.10.0
```

Also, I can seem to make Replibyte use the local_disk datastore as I define it. When I check the folder only a metadata file resides in. 

Am I missing something here? Or am I plain doing something wrong? Any help appreciated.

**Comment by mridude23** [comment]
Ok, so this might not have anything to do with Replibyte. I am now thinking there is something wrong with my data/relationships.
